### ISSUE TITLE
Explain properties of off-path time separation in privacy pass case

### ISSUE THREAD

**Issue by tfpauly** [intarchboard/draft-iab-privacy-partitioning#15]
The impacts section should talk about attestation, etc.

> ## Attestation (and identity management)
> 
> Simple techniques like encryption or a more flexible use of IP addresses, e.g. based on proxying, gives the user more control about its data and is a prerequisite for practical partitioning. This is especially important for metadata which have unintentionally been spread to more entities than functionally needed in the past. 
> 
> Looking further at the data that is requested by a service to function, and not only unintentionally revealed metadata, different services of course have different requirements. Some services do require a user identity, e.g. by creating a user account. Other services currently use existing identifiers like the IP address to create a notion of identity, e.g. to rate-limit access to a certain service or track their service usage. Particularly, in these cases there is a desire to minimize the number of entities that can identify the user. However, just concealing any identifying data by partitioning can impact the service function.
> 
> In these cases privacy partitioning can be “used” together with attestation where a known trusted entity that can access a user’s identity can attest a certain characteristic or property of the user without revealing the identity.
> 
> ToDo: Given an example?
>

**Comment by mirjak** [comment]
Not sure this belongs in the impact section.

**Comment by mirjak** [comment]
Actually I don't think we need this anymore. I mainly thought it would be useful to also define attestation in the context of this draft but I guess that is covered by the privacy pass section.

The interesting difference for privacy pass compared to the other approach is maybe that you have a "new" entity that is not on-path. A) this enables you to also do time partitioning, and b) this is something that can be combined with the other approaches. So I have the feeling the is something more we need to discuss here...

**Comment by tfpauly** [comment]
For privacy pass:
- Because the contexts are off-path they can be separated in time
- Depending on if the issuer is the same entity as the origin, you may _need_ to separate in time if you aren't going through a proxying attester
